// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: login/login.proto

package login

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OperateResponse 通用操作响应
type OperateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码（0=成功）
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperateResponse) Reset() {
	*x = OperateResponse{}
	mi := &file_login_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateResponse) ProtoMessage() {}

func (x *OperateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateResponse.ProtoReflect.Descriptor instead.
func (*OperateResponse) Descriptor() ([]byte, []int) {
	return file_login_login_proto_rawDescGZIP(), []int{0}
}

func (x *OperateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OperateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// LoginRequest 扫码登录请求
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_login_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_login_login_proto_rawDescGZIP(), []int{1}
}

// QRCodeResult 二维码结果
type QRCodeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                                   // 二维码 UUID
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                   // 二维码 Base64 数据
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`                                     // 二维码 URL
	CheckTime     uint32                 `protobuf:"varint,4,opt,name=check_time,json=checkTime,proto3" json:"check_time,omitempty"`       // 检查间隔时间（秒）
	ExpiredTime   uint32                 `protobuf:"varint,5,opt,name=expired_time,json=expiredTime,proto3" json:"expired_time,omitempty"` // 过期时间（秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QRCodeResult) Reset() {
	*x = QRCodeResult{}
	mi := &file_login_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QRCodeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRCodeResult) ProtoMessage() {}

func (x *QRCodeResult) ProtoReflect() protoreflect.Message {
	mi := &file_login_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRCodeResult.ProtoReflect.Descriptor instead.
func (*QRCodeResult) Descriptor() ([]byte, []int) {
	return file_login_login_proto_rawDescGZIP(), []int{2}
}

func (x *QRCodeResult) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *QRCodeResult) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *QRCodeResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *QRCodeResult) GetCheckTime() uint32 {
	if x != nil {
		return x.CheckTime
	}
	return 0
}

func (x *QRCodeResult) GetExpiredTime() uint32 {
	if x != nil {
		return x.ExpiredTime
	}
	return 0
}

// InitRequest 初始化请求
type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_login_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_login_login_proto_rawDescGZIP(), []int{3}
}

// InitResponse 初始化响应
type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码（0=成功）
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_login_login_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_login_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_login_login_proto_rawDescGZIP(), []int{4}
}

func (x *InitResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PasswordLoginRequest 密码登录请求
type PasswordLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`                       // 微信号/手机号
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                       // 密码（明文，会自动 MD5 加密）
	DeviceType    string                 `protobuf:"bytes,3,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"` // 设备类型：ipad/iphone，默认 ipad
	DeviceName    string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"` // 设备名称
	DeviceId      string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`       // 设备 ID（62 数据），可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordLoginRequest) Reset() {
	*x = PasswordLoginRequest{}
	mi := &file_login_login_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordLoginRequest) ProtoMessage() {}

func (x *PasswordLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_login_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordLoginRequest.ProtoReflect.Descriptor instead.
func (*PasswordLoginRequest) Descriptor() ([]byte, []int) {
	return file_login_login_proto_rawDescGZIP(), []int{5}
}

func (x *PasswordLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PasswordLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PasswordLoginRequest) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *PasswordLoginRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *PasswordLoginRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// PasswordLoginResult 密码登录结果
type PasswordLoginResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uin           uint32                 `protobuf:"varint,1,opt,name=uin,proto3" json:"uin,omitempty"`          // UIN
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"` // 用户名
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"` // 昵称
	Alias         string                 `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`       // 微信号
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`       // 邮箱
	Mobile        string                 `protobuf:"bytes,6,opt,name=mobile,proto3" json:"mobile,omitempty"`     // 手机号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordLoginResult) Reset() {
	*x = PasswordLoginResult{}
	mi := &file_login_login_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordLoginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordLoginResult) ProtoMessage() {}

func (x *PasswordLoginResult) ProtoReflect() protoreflect.Message {
	mi := &file_login_login_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordLoginResult.ProtoReflect.Descriptor instead.
func (*PasswordLoginResult) Descriptor() ([]byte, []int) {
	return file_login_login_proto_rawDescGZIP(), []int{6}
}

func (x *PasswordLoginResult) GetUin() uint32 {
	if x != nil {
		return x.Uin
	}
	return 0
}

func (x *PasswordLoginResult) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PasswordLoginResult) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PasswordLoginResult) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *PasswordLoginResult) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PasswordLoginResult) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

var File_login_login_proto protoreflect.FileDescriptor

const file_login_login_proto_rawDesc = "" +
	"\n" +
	"\x11login/login.proto\x12\x05login\"?\n" +
	"\x0fOperateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0e\n" +
	"\fLoginRequest\"\x8a\x01\n" +
	"\fQRCodeResult\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"check_time\x18\x04 \x01(\rR\tcheckTime\x12!\n" +
	"\fexpired_time\x18\x05 \x01(\rR\vexpiredTime\"\r\n" +
	"\vInitRequest\"<\n" +
	"\fInitResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xad\x01\n" +
	"\x14PasswordLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1f\n" +
	"\vdevice_type\x18\x03 \x01(\tR\n" +
	"deviceType\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\"\xa3\x01\n" +
	"\x13PasswordLoginResult\x12\x10\n" +
	"\x03uin\x18\x01 \x01(\rR\x03uin\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x16\n" +
	"\x06mobile\x18\x06 \x01(\tR\x06mobile2\xe2\x02\n" +
	"\fLoginService\x121\n" +
	"\x05Login\x12\x13.login.LoginRequest\x1a\x13.login.QRCodeResult\x12/\n" +
	"\x04Init\x12\x12.login.InitRequest\x1a\x13.login.InitResponse\x126\n" +
	"\aRefresh\x12\x13.login.LoginRequest\x1a\x16.login.OperateResponse\x125\n" +
	"\x06Wakeup\x12\x13.login.LoginRequest\x1a\x16.login.OperateResponse\x125\n" +
	"\x06Logout\x12\x13.login.LoginRequest\x1a\x16.login.OperateResponse\x12H\n" +
	"\rPasswordLogin\x12\x1b.login.PasswordLoginRequest\x1a\x1a.login.PasswordLoginResultBp\n" +
	"\tcom.loginB\n" +
	"LoginProtoP\x01Z#github.com/sbgayhub/golem/sdk/login\xa2\x02\x03LXX\xaa\x02\x05Login\xca\x02\x05Login\xe2\x02\x11Login\\GPBMetadata\xea\x02\x05Loginb\x06proto3"

var (
	file_login_login_proto_rawDescOnce sync.Once
	file_login_login_proto_rawDescData []byte
)

func file_login_login_proto_rawDescGZIP() []byte {
	file_login_login_proto_rawDescOnce.Do(func() {
		file_login_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_login_login_proto_rawDesc), len(file_login_login_proto_rawDesc)))
	})
	return file_login_login_proto_rawDescData
}

var file_login_login_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_login_login_proto_goTypes = []any{
	(*OperateResponse)(nil),      // 0: login.OperateResponse
	(*LoginRequest)(nil),         // 1: login.LoginRequest
	(*QRCodeResult)(nil),         // 2: login.QRCodeResult
	(*InitRequest)(nil),          // 3: login.InitRequest
	(*InitResponse)(nil),         // 4: login.InitResponse
	(*PasswordLoginRequest)(nil), // 5: login.PasswordLoginRequest
	(*PasswordLoginResult)(nil),  // 6: login.PasswordLoginResult
}
var file_login_login_proto_depIdxs = []int32{
	1, // 0: login.LoginService.Login:input_type -> login.LoginRequest
	3, // 1: login.LoginService.Init:input_type -> login.InitRequest
	1, // 2: login.LoginService.Refresh:input_type -> login.LoginRequest
	1, // 3: login.LoginService.Wakeup:input_type -> login.LoginRequest
	1, // 4: login.LoginService.Logout:input_type -> login.LoginRequest
	5, // 5: login.LoginService.PasswordLogin:input_type -> login.PasswordLoginRequest
	2, // 6: login.LoginService.Login:output_type -> login.QRCodeResult
	4, // 7: login.LoginService.Init:output_type -> login.InitResponse
	0, // 8: login.LoginService.Refresh:output_type -> login.OperateResponse
	0, // 9: login.LoginService.Wakeup:output_type -> login.OperateResponse
	0, // 10: login.LoginService.Logout:output_type -> login.OperateResponse
	6, // 11: login.LoginService.PasswordLogin:output_type -> login.PasswordLoginResult
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_login_login_proto_init() }
func file_login_login_proto_init() {
	if File_login_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_login_login_proto_rawDesc), len(file_login_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_login_login_proto_goTypes,
		DependencyIndexes: file_login_login_proto_depIdxs,
		MessageInfos:      file_login_login_proto_msgTypes,
	}.Build()
	File_login_login_proto = out.File
	file_login_login_proto_goTypes = nil
	file_login_login_proto_depIdxs = nil
}
